version: "3"

services:
  fail2ban:
    container_name: fail2ban
    hostname: fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=Asia/Taipei
      - F2B_DB_PURGE_AGE=365d
      - F2B_LOG_TARGET=/var/log/fortinet/fail2ban.log
    image: crazymax/fail2ban:latest
    command: >
          sh -c "apk add --update-cache py3-pip && pip3 install requests && pip3 install python-dotenv && pip install geoip2 && fail2ban-server -f -x -v start"    
    network_mode: host
    restart: always
    volumes:
      - ./fail2bandata:/data
      - ./geoip:/geoip
      - /var/log/fortinet:/var/log/fortinet
